version: 2.1

jobs:
  clone-and-build-repo:
    docker:
      - image: cimg/rust:1.58
    steps:
      - checkout
      - run: rustup target add wasm32-unknown-unknown
      - run: |
          git clone $(<./repo.txt) source
          cd source
          git cat-file -t $(<../commit-hash.txt)
          git checkout $(<../commit-hash.txt)
      - run: |
          rm -rf /tmp/artifacts/git
          mkdir -p /tmp/artifacts/git
          cp ./repo.txt /tmp/artifacts/git/repo.txt
          cd source
          git remote get-url $(git remote show) > /tmp/artifacts/git/remote.txt
          git rev-parse --abbrev-ref HEAD > /tmp/artifacts/git/branch.txt
          git rev-parse --verify HEAD > /tmp/artifacts/git/commit-hash.txt
      - store_artifacts:
          path: /tmp/artifacts/git
          destination: git
      - run: |
          rm -rf /tmp/artifacts
          mkdir -p /tmp/artifacts
      - run:
          # redirecting all output should allow no_output_timeout to timeout generally
          command: |
            cd "source/$(<./path.txt)"
            2>/tmp/artifacts/out/out.log 1>/tmp/artifacts/out/out.log ./near-verify.sh /tmp/artifacts/out/out.wasm
          no_output_timeout: 5m
      - store_artifacts:
          path: /tmp/artifacts/out
          destination: out

workflows:
  build:
    jobs:
      - clone-and-build-repo
