version: 2.1

jobs:
  clone-and-build-repo:
    docker:
      - image: cimg/rust:1.58
    steps:
      - checkout
      - run: git clone $(<repo) source
      - run: |
          cd source
          rustup target add wasm32-unknown-unknown
          cargo build --target wasm32-unknown-unknown --release
      - run: |
          rm -rf /tmp/artifacts
          mkdir -p /tmp/artifacts
          wasm_path="$(find ./target/wasm32-unknown-unknown/release/ -maxdepth 1 -name "*.wasm")"
          cp $wasm_path /tmp/artifacts/out.wasm
      - store_artifacts:
          path: /tmp/artifacts/out.wasm

workflows:
  build:
    jobs:
      - clone-and-build-repo
